[package]
name = "rust-tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.28.0"
rand = "0.8.5"
rodio = "0.20.0"
